---
database: postgres://aurora:aurora@database/aurora
port: 8545
network: testnet
endpoint: https://archival-rpc.testnet.near.org
engine: develop.aurora
signer: relay.aurora
blacklist:
  ipv4:
  ipv6:
